# Generated by Django 5.1.1 on 2024-09-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upiId',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phoneNo',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(related_name='groups', to='StudentManagement.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='StudentManagement.teacher')),
            ],
        ),
    ]
