# Generated by Django 5.1.1 on 2024-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_student_upiid_alter_student_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
    ]
