# Generated by Django 5.1.1 on 2024-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0003_alter_student_phoneno_alter_teacher_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classStudying',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.IntegerField(choices=[(1, 'Division 1'), (2, 'Division 2'), (3, 'Division 3'), (4, 'Division 4'), (5, 'Division 5'), (6, 'Division 6'), (7, 'Division 7'), (8, 'Division 8')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='upiHandle',
            field=models.CharField(choices=[('@oksbi', '@oksbi'), ('@okhdfc', '@okhdfc'), ('@okicici', '@okicici'), ('@okaxis', '@okaxis')], default='@oksbi', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='upiId',
            field=models.CharField(max_length=50),
        ),
    ]
