# Generated by Django 5.1.1 on 2024-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0004_remove_student_classstudying_remove_student_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.BigIntegerField(default=1),
        ),
    ]
