# Generated by Django 5.1.1 on 2024-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_alter_student_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
